### ISSUE TITLE
Duplicated, and questionable, logic for deciding when add/remove buttons should be shown.

### ISSUE THREAD

**Issue by lairdshaw** [Eldenroot/MyBB_Thank-you-like-plugin#169]
Lines [564](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/thankyoulike.php#L564)-585 of thankyoulike.php are essentially identical to lines [1171](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L1171)-1193 of inc/plugins/thankyoulike.php (with the minor differences being the variable being set in the eval()s, some of the comment wordings, and the indentation level). Better in my view would be to abstract this logic into a reusable function.

I am also not sure that the logic in this code is correct. In particular, I am concerned (taking the case of thankyoulike.php, but the same applies to inc/plugins/thankyoulike.php) that lines 578 and 583 are identical, making the conditional of line 576 redundant. This makes it difficult for me to understand what the purpose of the firstalloverwrite setting is - I looked at this part of the code in the first place to try to understand it, but only became more confused. Perhaps somebody in the know could explain what that setting is supposed to achieve, and then we can fix these conditionals?

**Comment by Eldenroot** [comment]
Our plugin was originally developed by -G33K-, then we overtook it (because he abandoned development) and made it compatible with MyBB v1.8.x... so some parts of code are not easy to understand, some parts are duplicated, etc. @SvePu made few PRs which cleaned up a code a little bit, but it would need more time and love to comment all parts tidy up more.

Feel free to work on it, I hope that @SvePu who is much more familiar with this plugin than me will add his reply.

**Comment by Eldenroot** [comment]
Added via https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/commit/1a5bb21a05088d66f12ab545e158dad2981422da
