### ISSUE TITLE
Should settings be in the usergroup and forum sections of the ACP where possible?

### ISSUE THREAD

**Issue by lairdshaw** [Eldenroot/MyBB_Thank-you-like-plugin#170]
Should the hideforgroups and hidelistforgroups settings be converted into per-usergroup settings to be shown in the usergroup section of the ACP like the tyl_limits_max and tyl_flood_interval settings are?

Similarly, should the exclude and excludecount settings be converted into per-forum settings to be shown in the forums section of the ACP (if this is even possible - I haven't checked)?

**Comment by Eldenroot** [comment]
> Should the hideforgroups and hidelistforgroups settings be converted into per-usergroup settings to be shown in the usergroup section of the ACP like the tyl_limits_max and tyl_flood_interval settings are?

I think that would be nice, BUT it has cons - now you can easily select usergroups in one page and see them all, so it is really easy to set... what if you have over 15 (or more) usergroups in your board, that would be time consuming to set everything from scratch after every update. This could be fixed by #168 

> Similarly, should the exclude and excludecount settings be converted into per-forum settings to be shown in the forums section of the ACP (if this is even possible - I haven't checked)?

Same as above, but again - every bigger board has a lot of forums/subforums etc, just imagine how time consuming that could be when you wanna to set these two parameters :(

**Comment by lairdshaw** [comment]
Good points - probably the best answer to both questions is "No".

**Comment by Eldenroot** [comment]
I am closing this now, maybe we can change it in future.
